spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/imagelite
    username: postgres
    password: postgres
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: update
    show-sql: true
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  
  
#spring:
#  application:
#    name: cambio-service
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/imagelite?useTimezone=true&serverTimezone=UTC
#    username: admin123
#    password: admin123
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    open-in-view: true